### PR TITLE
Updates and ESM support

### LINKED ISSUE #5: Support ESM test files
Once https://github.com/avajs/ava/issues/2345 has shipped it should be possible to configure AVA to load `ts` files as ES modules.

This means we need to import them, instead of using require.

We should also explore if there may be a way to configure this within the `typescript` configuration.

### PR DESCRIPTION
**Pull request by novemberborn**
Fixes #5.

- Simplify issue template
- Upgrade XO and apply changes
- Update dependencies
- Upgrade to ESM
- Match AVA 4 Node.js versions
- Update CI
- Support ESM files

### CODE REVIEW

**Comment by novemberborn** [comment]
Thwarted by CI failures! Why the heck is this failing in Node.js 12 and 14, but not locally?! https://github.com/avajs/typescript/runs/4072812179?check_suite_focus=true

Sure I can add `"lib": ["es2015"]` but that breaks linting: https://github.com/avajs/typescript/runs/4072834457?check_suite_focus=true

And why is it complaining about an ESLint type definition anyhow.

**Comment by sindresorhus** [comment]
> Thwarted by CI failures! Why the heck is this failing in Node.js 12 and 14, but not locally?!

Since it's only failing on Node.js 12 and 14, which use npm 6, not 7, I would guess it has something to do with dependency resolution. I had a lot of problems with npm 6 in XO... Try forcing the latest npm version maybe?

**Comment by sindresorhus** [comment]
Unrelated by both `actions/checkout@v1`, `actions/setup-node@v1`, and `codecov/codecov-action@v1` can be bumped to v2.

**Comment by novemberborn** [comment]
> Since it's only failing on Node.js 12 and 14, which use npm 6, not 7, I would guess it has something to do with dependency resolution. I had a lot of problems with npm 6 in XO... Try forcing the latest npm version maybe?

Yes, that does the trick! Well spotted.

> Unrelated by both `actions/checkout@v1`, `actions/setup-node@v1`, and `codecov/codecov-action@v1` can be bumped to v2.

Already taken care of in this PR 😄

**Pull request merged**
